### ISSUE TITLE
IOError: Couldn't read whole file

### ISSUE THREAD

**Issue by i5okie** [yabeda-rb/yabeda-prometheus-mmap#2]
Started seeing this recently:
```
IOError: Couldn't read whole file, read 28672, instead of 131072
/app/vendor/bundle/ruby/2.7.0/gems/prometheus-client-mmap-0.10.0/lib/prometheus/client/formats/text.rb:34:in `to_metrics'
/app/vendor/bundle/ruby/2.7.0/gems/prometheus-client-mmap-0.10.0/lib/prometheus/client/formats/text.rb:34:in `marshal_multiprocess'
/app/vendor/bundle/ruby/2.7.0/gems/prometheus-client-mmap-0.10.0/lib/prometheus/client/rack/exporter.rb:66:in `respond_with'
/app/vendor/bundle/ruby/2.7.0/gems/prometheus-client-mmap-0.10.0/lib/prometheus/client/rack/exporter.rb:27:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/yabeda-prometheus-mmap-0.1.0/lib/yabeda/prometheus/mmap/exporter.rb:51:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/show_exceptions.rb:23:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/usr/local/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

Is there anything in prometheus-mmap that could help deal with a situation, (im guessing) where process quits mid-write?

**Comment by Envek** [comment]
No idea. Do you still see such an error? @dsalahutdinov, any thoughts?
 
Sorry for the late reply,
